/**
 * Sidebar navigation configuration.
 * Each item has: to (route), label, permission, section (group heading), icon (section emoji).
 * The Layout component groups items by section, with collapsible accordion behaviour.
 */

export const SECTION_ICONS = {
  'Dashboard': '📊',
  'Student Portal': '🎓',
  'Student Management': '🎓',
  'Department & Staff': '🏛️',
  'Academic & LMS': '📖',
  'Course & Curriculum': '📚',
  'Examination & Results': '📝',
  'Attendance & Upload': '✅',
  'Fee & Finance': '💰',
  'Scholarship Management': '🎖️',
  'Payroll Management': '💵',
  'Expense Management': '📑',
  'Communication': '📡',
  'Library Management': '📕',
  'Inventory & Lab': '🔬',
  'Pharm.D / Hospital Training': '🏥',
  'Notice Board': '📌',
  'Internal Messaging': '💬',
  'Hostel Management': '🏠',
  'Transport Management': '🚌',
  'Placement Management': '💼',
  'Events & Seminars': '🎪',
  'Accreditation & NAAC': '🏆',
  'Reports & Analytics': '📈',
  'Audit & Security': '🔒',
  'Administration': '⚙️',
  'System Settings': '🔧',
  'Parent Portal': '👪',
};

export const NAV_ITEMS = [
  /* ── Dashboard ── */
  { to: '/', label: 'Dashboard', permission: 'dashboard:read', section: 'Dashboard' },

  /* ── Student Management ── */
  { to: '/students', label: 'All Students', permission: 'students:read', section: 'Student Management' },
  { to: '/admission', label: 'Admission', permission: 'students:read', section: 'Student Management' },
  { to: '/admission/merit-list', label: 'Merit List', permission: 'students:read', section: 'Student Management' },
  { to: '/students/alumni', label: 'Alumni', permission: 'students:read', section: 'Student Management' },

  /* ── Department & Staff ── */
  { to: '/departments', label: 'Departments', permission: 'departments:read', section: 'Department & Staff' },
  { to: '/staff', label: 'Staff Management', permission: 'staff:read', section: 'Department & Staff' },
  { to: '/staff/leave', label: 'Leave Requests', permission: 'staff:read', section: 'Department & Staff' },
  { to: '/staff/resignations', label: 'Resignations', permission: 'staff:read', section: 'Department & Staff' },

  /* ── Academic & LMS ── */
  { to: '/academic/syllabus', label: 'Syllabus Upload', permission: 'academic:read', section: 'Academic & LMS' },
  { to: '/academic/lesson-plans', label: 'Lesson Plans', permission: 'academic:read', section: 'Academic & LMS' },
  { to: '/academic/study-material', label: 'Study Material', permission: 'academic:read', section: 'Academic & LMS' },
  { to: '/academic/assignments', label: 'Assignments & Quizzes', permission: 'academic:read', section: 'Academic & LMS' },
  { to: '/academic/submission-feedback', label: 'Submission & Feedback', permission: 'academic:read', section: 'Academic & LMS' },
  { to: '/academic/blooms-taxonomy', label: "Bloom's Taxonomy", permission: 'academic:read', section: 'Academic & LMS' },
  { to: '/academic/co-po-mapping', label: 'CO–PO Mapping', permission: 'academic:read', section: 'Academic & LMS' },
  { to: '/academic/calendar', label: 'Academic Calendar', permission: 'academic:read', section: 'Academic & LMS' },
  { to: '/academic/lms-scorm', label: 'LMS / SCORM', permission: 'academic:read', section: 'Academic & LMS' },

  /* ── Course & Curriculum ── */
  { to: '/courses', label: 'Subjects', permission: 'courses:read', section: 'Course & Curriculum' },
  { to: '/semesters', label: 'Semesters', permission: 'courses:read', section: 'Course & Curriculum' },
  { to: '/subject-faculty', label: 'Subject–Faculty Mapping', permission: 'courses:read', section: 'Course & Curriculum' },
  { to: '/timetable', label: 'Timetable', permission: 'courses:read', section: 'Course & Curriculum' },

  /* ── Examination & Results ── */
  { to: '/exams', label: 'Examinations', permission: 'courses:read', section: 'Examination & Results' },
  { to: '/exams/internal-setup', label: 'Internal Exam Setup', permission: 'courses:read', section: 'Examination & Results' },
  { to: '/exams/university-scheduling', label: 'University Scheduling', permission: 'courses:read', section: 'Examination & Results' },
  { to: '/exams/seating', label: 'Seating Arrangement', permission: 'courses:read', section: 'Examination & Results' },
  { to: '/exams/marks-entry', label: 'Marks Entry', permission: 'courses:read', section: 'Examination & Results' },
  { to: '/exams/attendance-assignment-marks', label: 'Assignment Marks', permission: 'courses:read', section: 'Examination & Results' },
  { to: '/exams/total-grade', label: 'Grade Calculation', permission: 'courses:read', section: 'Examination & Results' },
  { to: '/exams/gpa-cgpa', label: 'GPA / CGPA', permission: 'courses:read', section: 'Examination & Results' },
  { to: '/exams/hall-ticket', label: 'Hall Ticket (QR)', permission: 'courses:read', section: 'Examination & Results' },
  { to: '/exams/result-approval', label: 'Result Approval', permission: 'courses:read', section: 'Examination & Results' },
  { to: '/exams/report-cards', label: 'Report Cards', permission: 'courses:read', section: 'Examination & Results' },
  { to: '/exams/revaluation-supplementary', label: 'Revaluation', permission: 'courses:read', section: 'Examination & Results' },
  { to: '/exams/topper-analytics', label: 'Topper Analytics', permission: 'courses:read', section: 'Examination & Results' },
  { to: '/results', label: 'Result Analytics', permission: 'courses:read', section: 'Examination & Results' },

  /* ── Attendance & Upload ── */
  { to: '/attendance', label: 'Attendance', permission: 'attendance:read', section: 'Attendance & Upload' },
  { to: '/bulk-upload', label: 'Bulk Excel Upload', permission: 'students:write', section: 'Attendance & Upload' },

  /* ── Fee & Finance ── */
  { to: '/fees', label: 'Fee Analytics', permission: 'fees:read', section: 'Fee & Finance' },
  { to: '/fees/structure', label: 'Fee Structure', permission: 'fees:read', section: 'Fee & Finance' },
  { to: '/fees/installments', label: 'Installments', permission: 'fees:read', section: 'Fee & Finance' },
  { to: '/fees/scholarships', label: 'Scholarships', permission: 'fees:read', section: 'Fee & Finance' },
  { to: '/fees/online-payments', label: 'Online Payments', permission: 'fees:read', section: 'Fee & Finance' },
  { to: '/fees/payment-tracking', label: 'Payment Tracking', permission: 'fees:read', section: 'Fee & Finance' },
  { to: '/fees/receipts', label: 'Receipts', permission: 'fees:read', section: 'Fee & Finance' },
  { to: '/fees/due-penalty', label: 'Due & Penalty', permission: 'fees:read', section: 'Fee & Finance' },
  { to: '/fees/refunds-concessions', label: 'Refunds & Concessions', permission: 'fees:read', section: 'Fee & Finance' },
  { to: '/fees/parent-view', label: 'Parent Fee View', permission: 'fees:read', section: 'Fee & Finance' },
  { to: '/fees/audit-logs', label: 'Fee Audit Logs', permission: 'fees:read', section: 'Fee & Finance' },
  { to: '/fees/gst-reports', label: 'GST Reports', permission: 'fees:read', section: 'Fee & Finance' },
  { to: '/fees/due-report', label: 'Due Report', permission: 'fees:read', section: 'Fee & Finance' },

  /* ── Scholarship Management ── */
  { to: '/scholarship/tracking', label: 'Scholarship Tracking', permission: 'scholarship:read', section: 'Scholarship Management' },
  { to: '/scholarship/government-records', label: 'Government Records', permission: 'scholarship:read', section: 'Scholarship Management' },
  { to: '/scholarship/approval-workflow', label: 'Approval Workflow', permission: 'scholarship:read', section: 'Scholarship Management' },

  /* ── Payroll Management ── */
  { to: '/payroll/salary-structure', label: 'Salary Structure', permission: 'payroll:read', section: 'Payroll Management' },
  { to: '/payroll/allowances', label: 'Allowances', permission: 'payroll:read', section: 'Payroll Management' },
  { to: '/payroll/deductions', label: 'Deductions', permission: 'payroll:read', section: 'Payroll Management' },
  { to: '/payroll/pf-esi', label: 'PF / ESI', permission: 'payroll:read', section: 'Payroll Management' },
  { to: '/payroll/payslip', label: 'Payslip Generation', permission: 'payroll:read', section: 'Payroll Management' },
  { to: '/payroll/salary-history', label: 'Salary History', permission: 'payroll:read', section: 'Payroll Management' },

  /* ── Expense Management ── */
  { to: '/expense/entry', label: 'Expense Entry', permission: 'expense:read', section: 'Expense Management' },
  { to: '/expense/category-wise', label: 'Category-wise', permission: 'expense:read', section: 'Expense Management' },
  { to: '/expense/monthly-report', label: 'Monthly Report', permission: 'expense:read', section: 'Expense Management' },
  { to: '/expense/budget-planning', label: 'Budget Planning', permission: 'expense:read', section: 'Expense Management' },

  /* ── Communication (merged) ── */
  { to: '/communication/bulk-sms', label: 'Bulk SMS', permission: 'communication:read', section: 'Communication' },
  { to: '/communication/whatsapp', label: 'WhatsApp', permission: 'communication:read', section: 'Communication' },
  { to: '/communication/email', label: 'Email', permission: 'communication:read', section: 'Communication' },
  { to: '/communication/push-notifications', label: 'Push Notifications', permission: 'communication:read', section: 'Communication' },
  { to: '/communication/department-messaging', label: 'Dept. Messaging', permission: 'communication:read', section: 'Communication' },
  { to: '/communication/scheduled-alerts', label: 'Scheduled Alerts', permission: 'communication:read', section: 'Communication' },
  { to: '/communication/emergency-broadcast', label: 'Emergency Broadcast', permission: 'communication:read', section: 'Communication' },
  { to: '/communication/delivery-status', label: 'Delivery Status', permission: 'communication:read', section: 'Communication' },
  { to: '/communication/read-receipts', label: 'Read Receipts', permission: 'communication:read', section: 'Communication' },
  { to: '/communication/auto-alerts', label: 'Auto-alerts', permission: 'communication:read', section: 'Communication' },
  { to: '/communication/fee-reminder-sms', label: 'Fee Reminder SMS', permission: 'communication:read', section: 'Communication' },
  { to: '/communication/attendance-alert-sms', label: 'Attendance Alert', permission: 'communication:read', section: 'Communication' },
  { to: '/communication/exam-notification', label: 'Exam Notification', permission: 'communication:read', section: 'Communication' },
  { to: '/communication/bulk-messaging', label: 'Bulk Messaging', permission: 'communication:read', section: 'Communication' },

  /* ── Library Management ── */
  { to: '/library/book-entry', label: 'Book Entry', permission: 'library:read', section: 'Library Management' },
  { to: '/library/isbn-tracking', label: 'ISBN Tracking', permission: 'library:read', section: 'Library Management' },
  { to: '/library/issue-return', label: 'Issue / Return', permission: 'library:read', section: 'Library Management' },
  { to: '/library/due-alerts', label: 'Due Tracking', permission: 'library:read', section: 'Library Management' },
  { to: '/library/fine-calculation', label: 'Fine Calculation', permission: 'library:read', section: 'Library Management' },
  { to: '/library/barcode-rfid', label: 'Barcode / RFID', permission: 'library:read', section: 'Library Management' },
  { to: '/library/accession-register', label: 'Accession Register', permission: 'library:read', section: 'Library Management' },
  { to: '/library/reservation', label: 'Reservation', permission: 'library:read', section: 'Library Management' },
  { to: '/library/history', label: 'History', permission: 'library:read', section: 'Library Management' },
  { to: '/library/stock-verification', label: 'Stock Verification', permission: 'library:read', section: 'Library Management' },
  { to: '/library/librarian-login', label: 'Librarian Login', permission: 'library:read', section: 'Library Management' },

  /* ── Inventory & Lab ── */
  { to: '/lab/chemical-stock', label: 'Chemical Stock', permission: 'lab:read', section: 'Inventory & Lab' },
  { to: '/lab/expiry-tracking', label: 'Expiry Alerts', permission: 'lab:read', section: 'Inventory & Lab' },
  { to: '/lab/equipment-inventory', label: 'Equipment', permission: 'lab:read', section: 'Inventory & Lab' },
  { to: '/lab/vendor-management', label: 'Vendors', permission: 'lab:read', section: 'Inventory & Lab' },
  { to: '/lab/purchase-orders', label: 'Purchase Orders', permission: 'lab:read', section: 'Inventory & Lab' },
  { to: '/lab/calibration-logs', label: 'Calibration Logs', permission: 'lab:read', section: 'Inventory & Lab' },
  { to: '/lab/manuals', label: 'Lab Manuals', permission: 'lab:read', section: 'Inventory & Lab' },
  { to: '/lab/practical-attendance', label: 'Practical Attendance', permission: 'lab:read', section: 'Inventory & Lab' },
  { to: '/lab/timetable', label: 'Lab Timetable', permission: 'lab:read', section: 'Inventory & Lab' },
  { to: '/lab/msds-storage', label: 'MSDS Storage', permission: 'lab:read', section: 'Inventory & Lab' },
  { to: '/lab/audit-reports', label: 'Audit Reports', permission: 'lab:read', section: 'Inventory & Lab' },

  /* ── Pharm.D / Hospital Training ── */
  { to: '/pharmd/posting-schedule', label: 'Posting Schedule', permission: 'pharmd:read', section: 'Pharm.D / Hospital Training' },
  { to: '/pharmd/mentor-login', label: 'Mentor Login', permission: 'pharmd:read', section: 'Pharm.D / Hospital Training' },
  { to: '/pharmd/case-sheets', label: 'Case Sheets', permission: 'pharmd:read', section: 'Pharm.D / Hospital Training' },
  { to: '/pharmd/reviews-feedback', label: 'Reviews & Feedback', permission: 'pharmd:read', section: 'Pharm.D / Hospital Training' },
  { to: '/pharmd/clinical-logbook', label: 'Clinical Logbook', permission: 'pharmd:read', section: 'Pharm.D / Hospital Training' },
  { to: '/pharmd/adr-reporting', label: 'ADR Reporting', permission: 'pharmd:read', section: 'Pharm.D / Hospital Training' },
  { to: '/pharmd/internship-assessment', label: 'Internship Assessment', permission: 'pharmd:read', section: 'Pharm.D / Hospital Training' },
  { to: '/pharmd/competency-scorecard', label: 'Competency Scorecard', permission: 'pharmd:read', section: 'Pharm.D / Hospital Training' },

  /* ── Notice Board ── */
  { to: '/notice/department', label: 'Department Notice', permission: 'notice:read', section: 'Notice Board' },
  { to: '/notice/role-based', label: 'Role-based Notice', permission: 'notice:read', section: 'Notice Board' },
  { to: '/notice/expiry', label: 'Expiry Date', permission: 'notice:read', section: 'Notice Board' },
  { to: '/notice/attachments', label: 'Attachments', permission: 'notice:read', section: 'Notice Board' },

  /* ── Internal Messaging ── */
  { to: '/messaging/student-staff', label: 'Student-Staff Chat', permission: 'messaging:read', section: 'Internal Messaging' },
  { to: '/messaging/group', label: 'Group Messaging', permission: 'messaging:read', section: 'Internal Messaging' },
  { to: '/messaging/announcements', label: 'Announcements', permission: 'messaging:read', section: 'Internal Messaging' },

  /* ── Hostel Management ── */
  { to: '/hostel/room-allocation', label: 'Room Allocation', permission: 'hostel:read', section: 'Hostel Management' },
  { to: '/hostel/bed-management', label: 'Bed Management', permission: 'hostel:read', section: 'Hostel Management' },
  { to: '/hostel/fees', label: 'Hostel Fee', permission: 'hostel:read', section: 'Hostel Management' },
  { to: '/hostel/mess-menu', label: 'Mess Tracking', permission: 'hostel:read', section: 'Hostel Management' },
  { to: '/hostel/visitor-logs', label: 'Visitor Log', permission: 'hostel:read', section: 'Hostel Management' },
  { to: '/hostel/check-in-out', label: 'Check-in/out', permission: 'hostel:read', section: 'Hostel Management' },
  { to: '/hostel/attendance', label: 'Hostel Attendance', permission: 'hostel:read', section: 'Hostel Management' },
  { to: '/hostel/alerts', label: 'Alerts', permission: 'hostel:read', section: 'Hostel Management' },

  /* ── Transport Management ── */
  { to: '/transport/route-bus', label: 'Bus Routes', permission: 'transport:read', section: 'Transport Management' },
  { to: '/transport/student-allocation', label: 'Student Allocation', permission: 'transport:read', section: 'Transport Management' },
  { to: '/transport/driver-vehicle', label: 'Driver & Vehicle', permission: 'transport:read', section: 'Transport Management' },
  { to: '/transport/bus-attendance', label: 'Route Attendance', permission: 'transport:read', section: 'Transport Management' },
  { to: '/transport/bus-pass', label: 'Bus Pass', permission: 'transport:read', section: 'Transport Management' },
  { to: '/transport/fees', label: 'Transport Fees', permission: 'transport:read', section: 'Transport Management' },
  { to: '/transport/route-change-approval', label: 'Route Change', permission: 'transport:read', section: 'Transport Management' },
  { to: '/transport/gps-tracking', label: 'GPS Tracking', permission: 'transport:read', section: 'Transport Management' },

  /* ── Placement Management ── */
  { to: '/placement/company-database', label: 'Companies', permission: 'placement:read', section: 'Placement Management' },
  { to: '/placement/campus-drives', label: 'Campus Drives', permission: 'placement:read', section: 'Placement Management' },
  { to: '/placement/student-eligibility-filter', label: 'Eligibility Filter', permission: 'placement:read', section: 'Placement Management' },
  { to: '/placement/selected-student-tracking', label: 'Selected Tracking', permission: 'placement:read', section: 'Placement Management' },
  { to: '/placement/cv-upload', label: 'CV Upload', permission: 'placement:read', section: 'Placement Management' },
  { to: '/placement/student-registration', label: 'Registration', permission: 'placement:read', section: 'Placement Management' },
  { to: '/placement/interview-tracking', label: 'Interview Tracking', permission: 'placement:read', section: 'Placement Management' },
  { to: '/placement/offer-letters', label: 'Offer Letters', permission: 'placement:read', section: 'Placement Management' },
  { to: '/placement/analytics', label: 'Placement Analytics', permission: 'placement:read', section: 'Placement Management' },
  { to: '/placement/alumni-interaction', label: 'Alumni Interaction', permission: 'placement:read', section: 'Placement Management' },

  /* ── Events & Seminars ── */
  { to: '/events/workshops', label: 'Workshops', permission: 'events:read', section: 'Events & Seminars' },
  { to: '/events/seminar-registration', label: 'Seminar Registration', permission: 'events:read', section: 'Events & Seminars' },
  { to: '/events/certificates', label: 'Certificates', permission: 'events:read', section: 'Events & Seminars' },

  /* ── Accreditation & NAAC ── */
  { to: '/accreditation/faculty-qualification', label: 'Faculty Qualification', permission: 'accreditation:read', section: 'Accreditation & NAAC' },
  { to: '/accreditation/student-strength', label: 'Student Strength', permission: 'accreditation:read', section: 'Accreditation & NAAC' },
  { to: '/accreditation/infrastructure', label: 'Infrastructure', permission: 'accreditation:read', section: 'Accreditation & NAAC' },
  { to: '/accreditation/research-publication', label: 'Research Publication', permission: 'accreditation:read', section: 'Accreditation & NAAC' },

  /* ── Reports & Analytics ── */
  { to: '/reports', label: 'Reports', permission: 'reports:read', section: 'Reports & Analytics' },
  { to: '/reports/builder', label: 'Report Builder', permission: 'reports:read', section: 'Reports & Analytics' },
  { to: '/reports/export-excel', label: 'Export to Excel', permission: 'reports:read', section: 'Reports & Analytics' },
  { to: '/reports/export-pdf', label: 'Export to PDF', permission: 'reports:read', section: 'Reports & Analytics' },
  { to: '/analytics', label: 'Charts Dashboard', permission: 'analytics:read', section: 'Reports & Analytics' },
  { to: '/analytics/department-performance', label: 'Dept. Performance', permission: 'analytics:read', section: 'Reports & Analytics' },

  /* ── Audit & Security ── */
  { to: '/audit', label: 'Audit Logs', permission: 'audit:read', section: 'Audit & Security' },
  { to: '/audit/activity', label: 'User Activity', permission: 'audit:read', section: 'Audit & Security' },
  { to: '/audit/login-logs', label: 'Login Logs', permission: 'audit:read', section: 'Audit & Security' },
  { to: '/audit/data-modification', label: 'Data Modification', permission: 'audit:read', section: 'Audit & Security' },
  { to: '/audit/security', label: 'Security Logs', permission: 'audit:read', section: 'Audit & Security' },

  /* ── Administration ── */
  { to: '/approvals', label: 'Approvals', permission: 'approvals:read', section: 'Administration' },
  { to: '/sessions', label: 'Sessions', permission: 'sessions:read', section: 'Administration' },
  { to: '/permissions', label: 'Roles & Permissions', permission: 'role_management:read', section: 'Administration' },
  { to: '/users', label: 'User Management', permission: 'users:read', section: 'Administration' },
  { to: '/profile', label: 'My Profile', permission: 'dashboard:read', section: 'Administration' },

  /* ── System Settings (Super Admin only) ── */
  { to: '/settings/backup', label: 'Backup & Restore', permission: 'role_management:write', section: 'System Settings' },
  { to: '/settings/payment-gateway', label: 'Payment Gateway Setup', permission: 'role_management:write', section: 'System Settings' },
  { to: '/settings/email', label: 'Email Configuration', permission: 'role_management:write', section: 'System Settings' },
  { to: '/settings/multi-campus', label: 'Multi-campus Setup', permission: 'role_management:write', section: 'System Settings' },

  /* ── Parent Portal ── */
  { to: '/parent', label: 'Parent Portal', permission: 'parent_portal:read', section: 'Parent Portal' },
  { to: '/parent-inbox', label: 'Parent Messages', permission: 'attendance:write', section: 'Parent Portal' },
];

/** Map route path to minimum permission required */
export const ROUTE_PERMISSION = {
  '/': 'dashboard:read',
  '/students': 'students:read',
  '/admission': 'students:read',
  '/admission/merit-list': 'students:read',
  '/students/alumni': 'students:read',
  '/students/promote': 'students:write',
  '/students/:id': 'students:read',
  '/departments': 'departments:read',
  '/staff': 'staff:read',
  '/staff/leave': 'staff:read',
  '/staff/resignations': 'staff:read',
  '/staff/:id': 'staff:read',
  '/academic/syllabus': 'academic:read',
  '/academic/lesson-plans': 'academic:read',
  '/academic/study-material': 'academic:read',
  '/academic/assignments': 'academic:read',
  '/academic/submission-feedback': 'academic:read',
  '/academic/blooms-taxonomy': 'academic:read',
  '/academic/co-po-mapping': 'academic:read',
  '/academic/calendar': 'academic:read',
  '/academic/lms-scorm': 'academic:read',
  '/courses': 'courses:read',
  '/semesters': 'courses:read',
  '/subject-faculty': 'courses:read',
  '/timetable': 'courses:read',
  '/exams/internal-setup': 'courses:read',
  '/exams/university-scheduling': 'courses:read',
  '/exams/seating': 'courses:read',
  '/exams/marks-entry': 'courses:read',
  '/exams/attendance-assignment-marks': 'courses:read',
  '/exams/total-grade': 'courses:read',
  '/exams/gpa-cgpa': 'courses:read',
  '/exams/hall-ticket': 'courses:read',
  '/exams/result-approval': 'courses:read',
  '/exams/report-cards': 'courses:read',
  '/exams/revaluation-supplementary': 'courses:read',
  '/exams/topper-analytics': 'courses:read',
  '/exams': 'courses:read',
  '/results': 'courses:read',
  '/attendance': 'attendance:read',
  '/bulk-upload': 'students:write',
  '/reports': 'reports:read',
  '/fees/structure': 'fees:read',
  '/fees/installments': 'fees:read',
  '/fees/scholarships': 'fees:read',
  '/fees/online-payments': 'fees:read',
  '/fees/payment-tracking': 'fees:read',
  '/fees/receipts': 'fees:read',
  '/fees/due-penalty': 'fees:read',
  '/fees/refunds-concessions': 'fees:read',
  '/fees/parent-view': 'fees:read',
  '/fees/audit-logs': 'fees:read',
  '/fees/gst-reports': 'fees:read',
  '/fees/due-report': 'fees:read',
  '/fees': 'fees:read',
  '/scholarship/tracking': 'scholarship:read',
  '/scholarship/government-records': 'scholarship:read',
  '/scholarship/approval-workflow': 'scholarship:read',
  '/payroll/salary-structure': 'payroll:read',
  '/payroll/allowances': 'payroll:read',
  '/payroll/deductions': 'payroll:read',
  '/payroll/pf-esi': 'payroll:read',
  '/payroll/payslip': 'payroll:read',
  '/payroll/salary-history': 'payroll:read',
  '/expense/entry': 'expense:read',
  '/expense/category-wise': 'expense:read',
  '/expense/monthly-report': 'expense:read',
  '/expense/budget-planning': 'expense:read',
  '/communication/bulk-sms': 'communication:read',
  '/communication/whatsapp': 'communication:read',
  '/communication/email': 'communication:read',
  '/communication/push-notifications': 'communication:read',
  '/communication/department-messaging': 'communication:read',
  '/communication/scheduled-alerts': 'communication:read',
  '/communication/emergency-broadcast': 'communication:read',
  '/communication/delivery-status': 'communication:read',
  '/communication/read-receipts': 'communication:read',
  '/communication/auto-alerts': 'communication:read',
  '/communication/fee-reminder-sms': 'communication:read',
  '/communication/attendance-alert-sms': 'communication:read',
  '/communication/exam-notification': 'communication:read',
  '/communication/bulk-messaging': 'communication:read',
  '/library/book-entry': 'library:read',
  '/library/isbn-tracking': 'library:read',
  '/library/accession-register': 'library:read',
  '/library/barcode-rfid': 'library:read',
  '/library/issue-return': 'library:read',
  '/library/due-alerts': 'library:read',
  '/library/fine-calculation': 'library:read',
  '/library/reservation': 'library:read',
  '/library/history': 'library:read',
  '/library/stock-verification': 'library:read',
  '/library/librarian-login': 'library:read',
  '/lab/chemical-stock': 'lab:read',
  '/lab/expiry-tracking': 'lab:read',
  '/lab/equipment-inventory': 'lab:read',
  '/lab/vendor-management': 'lab:read',
  '/lab/purchase-orders': 'lab:read',
  '/lab/calibration-logs': 'lab:read',
  '/lab/manuals': 'lab:read',
  '/lab/practical-attendance': 'lab:read',
  '/lab/timetable': 'lab:read',
  '/lab/msds-storage': 'lab:read',
  '/lab/audit-reports': 'lab:read',
  '/pharmd/posting-schedule': 'pharmd:read',
  '/pharmd/mentor-login': 'pharmd:read',
  '/pharmd/case-sheets': 'pharmd:read',
  '/pharmd/reviews-feedback': 'pharmd:read',
  '/pharmd/clinical-logbook': 'pharmd:read',
  '/pharmd/adr-reporting': 'pharmd:read',
  '/pharmd/internship-assessment': 'pharmd:read',
  '/pharmd/competency-scorecard': 'pharmd:read',
  '/notice/department': 'notice:read',
  '/notice/role-based': 'notice:read',
  '/notice/expiry': 'notice:read',
  '/notice/attachments': 'notice:read',
  '/messaging/student-staff': 'messaging:read',
  '/messaging/group': 'messaging:read',
  '/messaging/announcements': 'messaging:read',
  '/hostel/room-allocation': 'hostel:read',
  '/hostel/bed-management': 'hostel:read',
  '/hostel/check-in-out': 'hostel:read',
  '/hostel/attendance': 'hostel:read',
  '/hostel/visitor-logs': 'hostel:read',
  '/hostel/fees': 'hostel:read',
  '/hostel/mess-menu': 'hostel:read',
  '/hostel/alerts': 'hostel:read',
  '/transport/route-bus': 'transport:read',
  '/transport/student-allocation': 'transport:read',
  '/transport/driver-vehicle': 'transport:read',
  '/transport/bus-pass': 'transport:read',
  '/transport/fees': 'transport:read',
  '/transport/bus-attendance': 'transport:read',
  '/transport/route-change-approval': 'transport:read',
  '/transport/gps-tracking': 'transport:read',
  '/placement/company-database': 'placement:read',
  '/placement/campus-drives': 'placement:read',
  '/placement/student-eligibility-filter': 'placement:read',
  '/placement/selected-student-tracking': 'placement:read',
  '/placement/cv-upload': 'placement:read',
  '/placement/student-registration': 'placement:read',
  '/placement/interview-tracking': 'placement:read',
  '/placement/offer-letters': 'placement:read',
  '/placement/analytics': 'placement:read',
  '/placement/alumni-interaction': 'placement:read',
  '/events/workshops': 'events:read',
  '/events/seminar-registration': 'events:read',
  '/events/certificates': 'events:read',
  '/accreditation/faculty-qualification': 'accreditation:read',
  '/accreditation/student-strength': 'accreditation:read',
  '/accreditation/infrastructure': 'accreditation:read',
  '/accreditation/research-publication': 'accreditation:read',
  '/reports/builder': 'reports:read',
  '/reports/export-excel': 'reports:read',
  '/reports/export-pdf': 'reports:read',
  '/analytics': 'analytics:read',
  '/analytics/department-performance': 'analytics:read',
  '/audit/activity': 'audit:read',
  '/audit/login-logs': 'audit:read',
  '/audit/data-modification': 'audit:read',
  '/audit/security': 'audit:read',
  '/approvals': 'approvals:read',
  '/sessions': 'sessions:read',
  '/audit': 'audit:read',
  '/permissions': 'role_management:read',
  '/users': 'users:read',
  '/settings/backup': 'role_management:write',
  '/settings/payment-gateway': 'role_management:write',
  '/settings/email': 'role_management:write',
  '/settings/multi-campus': 'role_management:write',
  '/profile': 'dashboard:read',
  '/parent': 'parent_portal:read',
  '/parent-inbox': 'attendance:write',
};
