"""Dynamic navigation and route permissions. Served by GET /api/nav for frontend."""

NAV_ITEMS = [
    {"to": "/", "label": "Dashboard", "permission": "dashboard:read", "section": "Dashboard"},
    # Student Portal (student_portal:read) - students see only these
    {"to": "/timetable", "label": "My Timetable", "permission": "student_portal:read", "section": "Student Portal"},
    {"to": "/courses", "label": "My Subjects", "permission": "student_portal:read", "section": "Student Portal"},
    {"to": "/attendance", "label": "My Attendance", "permission": "student_portal:read", "section": "Student Portal"},
    {"to": "/student/marks", "label": "My Marks", "permission": "student_portal:read", "section": "Student Portal"},
    {"to": "/results", "label": "My Results", "permission": "student_portal:read", "section": "Student Portal"},
    {"to": "/exams/hall-ticket", "label": "Hall Ticket", "permission": "student_portal:read", "section": "Student Portal"},
    {"to": "/student/fees", "label": "Fee Structure", "permission": "student_portal:read", "section": "Student Portal"},
    {"to": "/student/payments", "label": "Payment History", "permission": "student_portal:read", "section": "Student Portal"},
    {"to": "/academic/study-material", "label": "Study Materials", "permission": "student_portal:read", "section": "Student Portal"},
    {"to": "/academic/assignments", "label": "Assignments", "permission": "student_portal:read", "section": "Student Portal"},
    {"to": "/student/notices", "label": "Notices", "permission": "student_portal:read", "section": "Student Portal"},
    {"to": "/student/messaging", "label": "Message Faculty", "permission": "student_portal:read", "section": "Student Portal"},
    {"to": "/student/certificates", "label": "Certificates", "permission": "student_portal:read", "section": "Student Portal"},
    {"to": "/students", "label": "Students", "permission": "students:read", "section": "Student Management"},
    {"to": "/admission", "label": "Admission", "permission": "students:read", "section": "Student Management"},
    {"to": "/admission/merit-list", "label": "Merit list", "permission": "students:read", "section": "Student Management"},
    {"to": "/students/alumni", "label": "Alumni", "permission": "students:read", "section": "Student Management"},
    {"to": "/departments", "label": "Departments", "permission": "departments:read", "section": "Department & Staff"},
    {"to": "/staff", "label": "Staff Management", "permission": "staff:read", "section": "Department & Staff"},
    {"to": "/staff/leave", "label": "Staff leave", "permission": "staff:read", "section": "Department & Staff"},
    {"to": "/staff/resignations", "label": "Resignations", "permission": "staff:read", "section": "Department & Staff"},
    {"to": "/academic/syllabus", "label": "Syllabus upload", "permission": "academic:read", "section": "Academic & LMS"},
    {"to": "/academic/lesson-plans", "label": "Lesson plans", "permission": "academic:read", "section": "Academic & LMS"},
    {"to": "/academic/study-material", "label": "Study material (PDF / PPT / Video)", "permission": "academic:read", "section": "Academic & LMS"},
    {"to": "/academic/assignments", "label": "Assignments & quizzes", "permission": "academic:read", "section": "Academic & LMS"},
    {"to": "/academic/submission-feedback", "label": "Submission & feedback", "permission": "academic:read", "section": "Academic & LMS"},
    {"to": "/academic/blooms-taxonomy", "label": "Bloom's taxonomy", "permission": "academic:read", "section": "Academic & LMS"},
    {"to": "/academic/co-po-mapping", "label": "CO–PO mapping", "permission": "academic:read", "section": "Academic & LMS"},
    {"to": "/academic/calendar", "label": "Academic calendar", "permission": "academic:read", "section": "Academic & LMS"},
    {"to": "/academic/lms-scorm", "label": "LMS / SCORM integration", "permission": "academic:read", "section": "Academic & LMS"},
    {"to": "/courses", "label": "Subjects", "permission": "courses:read", "section": "Course & Curriculum"},
    {"to": "/semesters", "label": "Semesters", "permission": "courses:read", "section": "Course & Curriculum"},
    {"to": "/subject-faculty", "label": "Subject–Faculty", "permission": "courses:read", "section": "Course & Curriculum"},
    {"to": "/timetable", "label": "Timetable", "permission": "courses:read", "section": "Course & Curriculum"},
    {"to": "/exams/internal-setup", "label": "Internal exam setup", "permission": "courses:read", "section": "Examination & Results"},
    {"to": "/exams/university-scheduling", "label": "University exam scheduling", "permission": "courses:read", "section": "Examination & Results"},
    {"to": "/exams/seating", "label": "Seating arrangement", "permission": "courses:read", "section": "Examination & Results"},
    {"to": "/exams/marks-entry", "label": "Marks entry (internal / practical)", "permission": "courses:read", "section": "Examination & Results"},
    {"to": "/exams/attendance-assignment-marks", "label": "Attendance & assignment marks", "permission": "courses:read", "section": "Examination & Results"},
    {"to": "/exams/total-grade", "label": "Total & grade calculation", "permission": "courses:read", "section": "Examination & Results"},
    {"to": "/exams/gpa-cgpa", "label": "GPA / CGPA", "permission": "courses:read", "section": "Examination & Results"},
    {"to": "/exams/hall-ticket", "label": "Hall ticket (QR)", "permission": "courses:read", "section": "Examination & Results"},
    {"to": "/exams/result-approval", "label": "Result approval", "permission": "courses:read", "section": "Examination & Results"},
    {"to": "/exams/report-cards", "label": "Report cards", "permission": "courses:read", "section": "Examination & Results"},
    {"to": "/exams/revaluation-supplementary", "label": "Revaluation & supplementary", "permission": "courses:read", "section": "Examination & Results"},
    {"to": "/exams/topper-analytics", "label": "Topper analytics", "permission": "courses:read", "section": "Examination & Results"},
    {"to": "/exams", "label": "Examinations", "permission": "courses:read", "section": "Examination & Results"},
    {"to": "/results", "label": "Result & Analytics", "permission": "courses:read", "section": "Examination & Results"},
    {"to": "/attendance", "label": "Attendance", "permission": "attendance:read", "section": "Attendance & Upload"},
    {"to": "/bulk-upload", "label": "Bulk Excel upload", "permission": "students:write", "section": "Attendance & Upload"},
    {"to": "/reports", "label": "Reports", "permission": "reports:read", "section": "Reports & Analytics"},
    {"to": "/fees/structure", "label": "Course-wise fee structure", "permission": "fees:read", "section": "Fee & Finance"},
    {"to": "/fees/installments", "label": "Installments", "permission": "fees:read", "section": "Fee & Finance"},
    {"to": "/fees/scholarships", "label": "Scholarships", "permission": "fees:read", "section": "Fee & Finance"},
    {"to": "/fees/online-payments", "label": "Online payments", "permission": "fees:read", "section": "Fee & Finance"},
    {"to": "/fees/payment-tracking", "label": "Cash / UPI / Bank tracking", "permission": "fees:read", "section": "Fee & Finance"},
    {"to": "/fees/receipts", "label": "Receipt generation", "permission": "fees:read", "section": "Fee & Finance"},
    {"to": "/fees/due-penalty", "label": "Due & penalty automation", "permission": "fees:read", "section": "Fee & Finance"},
    {"to": "/fees/refunds-concessions", "label": "Refunds & concessions", "permission": "fees:read", "section": "Fee & Finance"},
    {"to": "/fees/parent-view", "label": "Parent fee view", "permission": "fees:read", "section": "Fee & Finance"},
    {"to": "/fees/audit-logs", "label": "Audit logs", "permission": "fees:read", "section": "Fee & Finance"},
    {"to": "/fees/gst-reports", "label": "GST reports", "permission": "fees:read", "section": "Fee & Finance"},
    {"to": "/fees/due-report", "label": "Due report", "permission": "fees:read", "section": "Fee & Finance"},
    {"to": "/fees", "label": "Fee analytics", "permission": "fees:read", "section": "Fee & Finance"},
    {"to": "/scholarship/tracking", "label": "Scholarship tracking", "permission": "scholarship:read", "section": "Scholarship Management"},
    {"to": "/scholarship/government-records", "label": "Government scholarship records", "permission": "scholarship:read", "section": "Scholarship Management"},
    {"to": "/scholarship/approval-workflow", "label": "Approval workflow", "permission": "scholarship:read", "section": "Scholarship Management"},
    {"to": "/payroll/salary-structure", "label": "Salary structure", "permission": "payroll:read", "section": "Payroll Management"},
    {"to": "/payroll/allowances", "label": "Allowances", "permission": "payroll:read", "section": "Payroll Management"},
    {"to": "/payroll/deductions", "label": "Deductions", "permission": "payroll:read", "section": "Payroll Management"},
    {"to": "/payroll/pf-esi", "label": "PF/ESI tracking", "permission": "payroll:read", "section": "Payroll Management"},
    {"to": "/payroll/payslip", "label": "Payslip generation", "permission": "payroll:read", "section": "Payroll Management"},
    {"to": "/payroll/salary-history", "label": "Salary history", "permission": "payroll:read", "section": "Payroll Management"},
    {"to": "/expense/entry", "label": "College expense entry", "permission": "expense:read", "section": "Expense Management"},
    {"to": "/expense/category-wise", "label": "Category wise expenses", "permission": "expense:read", "section": "Expense Management"},
    {"to": "/expense/monthly-report", "label": "Monthly expense report", "permission": "expense:read", "section": "Expense Management"},
    {"to": "/expense/budget-planning", "label": "Budget planning", "permission": "expense:read", "section": "Expense Management"},
    {"to": "/communication/bulk-sms", "label": "Bulk SMS", "permission": "communication:read", "section": "Communication"},
    {"to": "/communication/whatsapp", "label": "WhatsApp", "permission": "communication:read", "section": "Communication"},
    {"to": "/communication/email", "label": "Email", "permission": "communication:read", "section": "Communication"},
    {"to": "/communication/push-notifications", "label": "Push notifications", "permission": "communication:read", "section": "Communication"},
    {"to": "/communication/department-messaging", "label": "Department messaging", "permission": "communication:read", "section": "Communication"},
    {"to": "/communication/scheduled-alerts", "label": "Scheduled alerts", "permission": "communication:read", "section": "Communication"},
    {"to": "/communication/emergency-broadcast", "label": "Emergency broadcast", "permission": "communication:read", "section": "Communication"},
    {"to": "/communication/delivery-status", "label": "Delivery status", "permission": "communication:read", "section": "Communication"},
    {"to": "/communication/read-receipts", "label": "Read receipts", "permission": "communication:read", "section": "Communication"},
    {"to": "/communication/auto-alerts", "label": "Auto-alerts", "permission": "communication:read", "section": "Communication"},
    {"to": "/communication/fee-reminder-sms", "label": "Fee reminder SMS", "permission": "communication:read", "section": "Communication"},
    {"to": "/communication/attendance-alert-sms", "label": "Attendance alert SMS", "permission": "communication:read", "section": "Communication"},
    {"to": "/communication/exam-notification", "label": "Exam notification", "permission": "communication:read", "section": "Communication"},
    {"to": "/communication/bulk-messaging", "label": "Bulk messaging", "permission": "communication:read", "section": "Communication"},
    {"to": "/library/book-entry", "label": "Book entry", "permission": "library:read", "section": "Library Management"},
    {"to": "/library/isbn-tracking", "label": "ISBN tracking", "permission": "library:read", "section": "Library Management"},
    {"to": "/library/issue-return", "label": "Issue/Return", "permission": "library:read", "section": "Library Management"},
    {"to": "/library/due-alerts", "label": "Due tracking", "permission": "library:read", "section": "Library Management"},
    {"to": "/library/fine-calculation", "label": "Fine calculation", "permission": "library:read", "section": "Library Management"},
    {"to": "/library/barcode-rfid", "label": "Barcode ready", "permission": "library:read", "section": "Library Management"},
    {"to": "/library/accession-register", "label": "Accession register", "permission": "library:read", "section": "Library Management"},
    {"to": "/library/reservation", "label": "Reservation", "permission": "library:read", "section": "Library Management"},
    {"to": "/library/history", "label": "History", "permission": "library:read", "section": "Library Management"},
    {"to": "/library/stock-verification", "label": "Stock verification", "permission": "library:read", "section": "Library Management"},
    {"to": "/library/librarian-login", "label": "Librarian login", "permission": "library:read", "section": "Library Management"},
    {"to": "/lab/chemical-stock", "label": "Chemical stock tracking", "permission": "lab:read", "section": "Inventory & Lab"},
    {"to": "/lab/expiry-tracking", "label": "Expiry date alert", "permission": "lab:read", "section": "Inventory & Lab"},
    {"to": "/lab/equipment-inventory", "label": "Equipment tracking", "permission": "lab:read", "section": "Inventory & Lab"},
    {"to": "/lab/vendor-management", "label": "Vendor management", "permission": "lab:read", "section": "Inventory & Lab"},
    {"to": "/lab/purchase-orders", "label": "Purchase order management", "permission": "lab:read", "section": "Inventory & Lab"},
    {"to": "/lab/calibration-logs", "label": "Calibration logs", "permission": "lab:read", "section": "Inventory & Lab"},
    {"to": "/lab/manuals", "label": "Lab manuals", "permission": "lab:read", "section": "Inventory & Lab"},
    {"to": "/lab/practical-attendance", "label": "Practical attendance", "permission": "lab:read", "section": "Inventory & Lab"},
    {"to": "/lab/timetable", "label": "Lab timetable", "permission": "lab:read", "section": "Inventory & Lab"},
    {"to": "/lab/msds-storage", "label": "MSDS storage", "permission": "lab:read", "section": "Inventory & Lab"},
    {"to": "/lab/audit-reports", "label": "Audit reports", "permission": "lab:read", "section": "Inventory & Lab"},
    {"to": "/pharmd/posting-schedule", "label": "Posting schedule", "permission": "pharmd:read", "section": "Pharm.D / Hospital Training"},
    {"to": "/pharmd/mentor-login", "label": "Mentor login", "permission": "pharmd:read", "section": "Pharm.D / Hospital Training"},
    {"to": "/pharmd/case-sheets", "label": "Case sheets", "permission": "pharmd:read", "section": "Pharm.D / Hospital Training"},
    {"to": "/pharmd/reviews-feedback", "label": "Reviews & feedback", "permission": "pharmd:read", "section": "Pharm.D / Hospital Training"},
    {"to": "/pharmd/clinical-logbook", "label": "Clinical logbook", "permission": "pharmd:read", "section": "Pharm.D / Hospital Training"},
    {"to": "/pharmd/adr-reporting", "label": "ADR reporting", "permission": "pharmd:read", "section": "Pharm.D / Hospital Training"},
    {"to": "/pharmd/internship-assessment", "label": "Internship assessment", "permission": "pharmd:read", "section": "Pharm.D / Hospital Training"},
    {"to": "/pharmd/competency-scorecard", "label": "Competency scorecard", "permission": "pharmd:read", "section": "Pharm.D / Hospital Training"},
    {"to": "/notice/department", "label": "Department notice", "permission": "notice:read", "section": "Notice Board"},
    {"to": "/notice/role-based", "label": "Role based notice", "permission": "notice:read", "section": "Notice Board"},
    {"to": "/notice/expiry", "label": "Expiry date", "permission": "notice:read", "section": "Notice Board"},
    {"to": "/notice/attachments", "label": "Attachments", "permission": "notice:read", "section": "Notice Board"},
    {"to": "/messaging/student-staff", "label": "Student ↔ Staff messaging", "permission": "messaging:read", "section": "Internal Messaging"},
    {"to": "/messaging/group", "label": "Group messaging", "permission": "messaging:read", "section": "Internal Messaging"},
    {"to": "/messaging/announcements", "label": "Announcement system", "permission": "messaging:read", "section": "Internal Messaging"},
    {"to": "/hostel/room-allocation", "label": "Room allocation", "permission": "hostel:read", "section": "Hostel Management"},
    {"to": "/hostel/bed-management", "label": "Bed management", "permission": "hostel:read", "section": "Hostel Management"},
    {"to": "/hostel/fees", "label": "Hostel fee", "permission": "hostel:read", "section": "Hostel Management"},
    {"to": "/hostel/mess-menu", "label": "Mess tracking", "permission": "hostel:read", "section": "Hostel Management"},
    {"to": "/hostel/visitor-logs", "label": "Visitor log", "permission": "hostel:read", "section": "Hostel Management"},
    {"to": "/hostel/check-in-out", "label": "Check-in/out", "permission": "hostel:read", "section": "Hostel Management"},
    {"to": "/hostel/attendance", "label": "Hostel attendance", "permission": "hostel:read", "section": "Hostel Management"},
    {"to": "/hostel/alerts", "label": "Alerts", "permission": "hostel:read", "section": "Hostel Management"},
    {"to": "/transport/route-bus", "label": "Bus routes", "permission": "transport:read", "section": "Transport Management"},
    {"to": "/transport/student-allocation", "label": "Student allocation", "permission": "transport:read", "section": "Transport Management"},
    {"to": "/transport/driver-vehicle", "label": "Driver details", "permission": "transport:read", "section": "Transport Management"},
    {"to": "/transport/bus-attendance", "label": "Route attendance", "permission": "transport:read", "section": "Transport Management"},
    {"to": "/transport/bus-pass", "label": "Bus pass", "permission": "transport:read", "section": "Transport Management"},
    {"to": "/transport/fees", "label": "Transport fees", "permission": "transport:read", "section": "Transport Management"},
    {"to": "/transport/route-change-approval", "label": "Route change approval", "permission": "transport:read", "section": "Transport Management"},
    {"to": "/transport/gps-tracking", "label": "GPS tracking", "permission": "transport:read", "section": "Transport Management"},
    {"to": "/placement/company-database", "label": "Company registration", "permission": "placement:read", "section": "Placement Management"},
    {"to": "/placement/campus-drives", "label": "Drive scheduling", "permission": "placement:read", "section": "Placement Management"},
    {"to": "/placement/student-eligibility-filter", "label": "Student eligibility filter", "permission": "placement:read", "section": "Placement Management"},
    {"to": "/placement/selected-student-tracking", "label": "Selected student tracking", "permission": "placement:read", "section": "Placement Management"},
    {"to": "/placement/cv-upload", "label": "CV upload", "permission": "placement:read", "section": "Placement Management"},
    {"to": "/placement/student-registration", "label": "Student registration", "permission": "placement:read", "section": "Placement Management"},
    {"to": "/placement/interview-tracking", "label": "Interview tracking", "permission": "placement:read", "section": "Placement Management"},
    {"to": "/placement/offer-letters", "label": "Offer letters", "permission": "placement:read", "section": "Placement Management"},
    {"to": "/placement/analytics", "label": "Placement analytics", "permission": "placement:read", "section": "Placement Management"},
    {"to": "/placement/alumni-interaction", "label": "Alumni interaction", "permission": "placement:read", "section": "Placement Management"},
    {"to": "/events/workshops", "label": "Workshop tracking", "permission": "events:read", "section": "Events & Seminars"},
    {"to": "/events/seminar-registration", "label": "Seminar registration", "permission": "events:read", "section": "Events & Seminars"},
    {"to": "/events/certificates", "label": "Certificate generation", "permission": "events:read", "section": "Events & Seminars"},
    {"to": "/accreditation/faculty-qualification", "label": "Faculty qualification report", "permission": "accreditation:read", "section": "Accreditation & NAAC"},
    {"to": "/accreditation/student-strength", "label": "Student strength report", "permission": "accreditation:read", "section": "Accreditation & NAAC"},
    {"to": "/accreditation/infrastructure", "label": "Infrastructure report", "permission": "accreditation:read", "section": "Accreditation & NAAC"},
    {"to": "/accreditation/research-publication", "label": "Research publication record", "permission": "accreditation:read", "section": "Accreditation & NAAC"},
    {"to": "/reports/builder", "label": "Custom report builder", "permission": "reports:read", "section": "Reports & Analytics"},
    {"to": "/reports/export-excel", "label": "Export to Excel", "permission": "reports:read", "section": "Reports & Analytics"},
    {"to": "/reports/export-pdf", "label": "Export to PDF", "permission": "reports:read", "section": "Reports & Analytics"},
    {"to": "/analytics", "label": "Graphical dashboard", "permission": "analytics:read", "section": "Reports & Analytics"},
    {"to": "/analytics/department-performance", "label": "Department performance analytics", "permission": "analytics:read", "section": "Reports & Analytics"},
    {"to": "/reports", "label": "Reports", "permission": "reports:read", "section": "Reports & Analytics"},
    {"to": "/audit/activity", "label": "User activity tracking", "permission": "audit:read", "section": "Audit & Security"},
    {"to": "/audit/login-logs", "label": "Login logs", "permission": "audit:read", "section": "Audit & Security"},
    {"to": "/audit/data-modification", "label": "Data modification logs", "permission": "audit:read", "section": "Audit & Security"},
    {"to": "/audit/security", "label": "Security logs", "permission": "audit:read", "section": "Audit & Security"},
    {"to": "/audit", "label": "Audit logs", "permission": "audit:read", "section": "Audit & Security"},
    {"to": "/approvals", "label": "Approvals", "permission": "approvals:read", "section": "Administration"},
    {"to": "/sessions", "label": "Sessions", "permission": "sessions:read", "section": "Administration"},
    {"to": "/permissions", "label": "Role & permissions", "permission": "role_management:read", "section": "Administration"},
    {"to": "/users", "label": "User management", "permission": "users:read", "section": "Administration"},
    {"to": "/settings/backup", "label": "Backup & restore", "permission": "role_management:write", "section": "System Settings"},
    {"to": "/settings/payment-gateway", "label": "Payment gateway setup", "permission": "role_management:write", "section": "System Settings"},
    {"to": "/settings/email", "label": "Email configuration", "permission": "role_management:write", "section": "System Settings"},
    {"to": "/settings/multi-campus", "label": "Multi-campus setup", "permission": "role_management:write", "section": "System Settings"},
    {"to": "/profile", "label": "My profile", "permission": "dashboard:read", "section": "Administration"},
    {"to": "/parent", "label": "Parent portal", "permission": "parent_portal:read", "section": "Parent Portal"},
    {"to": "/parent-inbox", "label": "Parent messages", "permission": "attendance:write", "section": "Parent Portal"},
]

ROUTE_PERMISSIONS = {
    "/": "dashboard:read",
    "/students": "students:read",
    "/admission": "students:read",
    "/admission/merit-list": "students:read",
    "/students/alumni": "students:read",
    "/students/promote": "students:write",
    "/students/:id": "students:read",
    "/departments": "departments:read",
    "/staff": "staff:read",
    "/staff/leave": "staff:read",
    "/staff/resignations": "staff:read",
    "/staff/:id": "staff:read",
    "/academic/syllabus": "academic:read",
    "/academic/lesson-plans": "academic:read",
    "/academic/study-material": "academic:read|student_portal:read",
    "/academic/assignments": "academic:read|student_portal:read",
    "/academic/submission-feedback": "academic:read",
    "/academic/blooms-taxonomy": "academic:read",
    "/academic/co-po-mapping": "academic:read",
    "/academic/calendar": "academic:read",
    "/academic/lms-scorm": "academic:read",
    "/courses": "courses:read|student_portal:read",
    "/semesters": "courses:read",
    "/subject-faculty": "courses:read",
    "/timetable": "courses:read|student_portal:read",
    "/exams/internal-setup": "courses:read",
    "/exams/university-scheduling": "courses:read",
    "/exams/seating": "courses:read",
    "/exams/marks-entry": "courses:read",
    "/exams/attendance-assignment-marks": "courses:read",
    "/exams/total-grade": "courses:read",
    "/exams/gpa-cgpa": "courses:read",
    "/exams/hall-ticket": "courses:read|student_portal:read",
    "/exams/result-approval": "courses:read",
    "/exams/report-cards": "courses:read",
    "/exams/revaluation-supplementary": "courses:read",
    "/exams/topper-analytics": "courses:read",
    "/exams": "courses:read",
    "/results": "courses:read|student_portal:read",
    "/attendance": "attendance:read|student_portal:read",
    "/bulk-upload": "students:write",
    "/reports": "reports:read",
    "/fees/structure": "fees:read",
    "/fees/installments": "fees:read",
    "/fees/scholarships": "fees:read",
    "/fees/online-payments": "fees:read",
    "/fees/payment-tracking": "fees:read",
    "/fees/receipts": "fees:read",
    "/fees/due-penalty": "fees:read",
    "/fees/refunds-concessions": "fees:read",
    "/fees/parent-view": "fees:read",
    "/fees/audit-logs": "fees:read",
    "/fees/gst-reports": "fees:read",
    "/fees/due-report": "fees:read",
    "/fees": "fees:read",
    "/scholarship/tracking": "scholarship:read",
    "/scholarship/government-records": "scholarship:read",
    "/scholarship/approval-workflow": "scholarship:read",
    "/payroll/salary-structure": "payroll:read",
    "/payroll/allowances": "payroll:read",
    "/payroll/deductions": "payroll:read",
    "/payroll/pf-esi": "payroll:read",
    "/payroll/payslip": "payroll:read",
    "/payroll/salary-history": "payroll:read",
    "/expense/entry": "expense:read",
    "/expense/category-wise": "expense:read",
    "/expense/monthly-report": "expense:read",
    "/expense/budget-planning": "expense:read",
    "/communication/bulk-sms": "communication:read",
    "/communication/whatsapp": "communication:read",
    "/communication/email": "communication:read",
    "/communication/push-notifications": "communication:read",
    "/communication/department-messaging": "communication:read",
    "/communication/scheduled-alerts": "communication:read",
    "/communication/emergency-broadcast": "communication:read",
    "/communication/delivery-status": "communication:read",
    "/communication/read-receipts": "communication:read",
    "/communication/auto-alerts": "communication:read",
    "/communication/fee-reminder-sms": "communication:read",
    "/communication/attendance-alert-sms": "communication:read",
    "/communication/exam-notification": "communication:read",
    "/communication/bulk-messaging": "communication:read",
    "/library/book-entry": "library:read",
    "/library/isbn-tracking": "library:read",
    "/library/accession-register": "library:read",
    "/library/barcode-rfid": "library:read",
    "/library/issue-return": "library:read",
    "/library/due-alerts": "library:read",
    "/library/fine-calculation": "library:read",
    "/library/reservation": "library:read",
    "/library/due-alerts": "library:read",
    "/library/history": "library:read",
    "/library/stock-verification": "library:read",
    "/library/librarian-login": "library:read",
    "/lab/chemical-stock": "lab:read",
    "/lab/expiry-tracking": "lab:read",
    "/lab/equipment-inventory": "lab:read",
    "/lab/vendor-management": "lab:read",
    "/lab/purchase-orders": "lab:read",
    "/lab/calibration-logs": "lab:read",
    "/lab/manuals": "lab:read",
    "/lab/practical-attendance": "lab:read",
    "/lab/timetable": "lab:read",
    "/lab/msds-storage": "lab:read",
    "/lab/audit-reports": "lab:read",
    "/pharmd/posting-schedule": "pharmd:read",
    "/pharmd/mentor-login": "pharmd:read",
    "/pharmd/case-sheets": "pharmd:read",
    "/pharmd/reviews-feedback": "pharmd:read",
    "/pharmd/clinical-logbook": "pharmd:read",
    "/pharmd/adr-reporting": "pharmd:read",
    "/pharmd/internship-assessment": "pharmd:read",
    "/pharmd/competency-scorecard": "pharmd:read",
    "/notice/department": "notice:read",
    "/notice/role-based": "notice:read",
    "/notice/expiry": "notice:read",
    "/notice/attachments": "notice:read",
    "/messaging/student-staff": "messaging:read",
    "/messaging/group": "messaging:read",
    "/messaging/announcements": "messaging:read",
    "/hostel/room-allocation": "hostel:read",
    "/hostel/bed-management": "hostel:read",
    "/hostel/check-in-out": "hostel:read",
    "/hostel/attendance": "hostel:read",
    "/hostel/visitor-logs": "hostel:read",
    "/hostel/fees": "hostel:read",
    "/hostel/mess-menu": "hostel:read",
    "/hostel/alerts": "hostel:read",
    "/transport/route-bus": "transport:read",
    "/transport/student-allocation": "transport:read",
    "/transport/driver-vehicle": "transport:read",
    "/transport/bus-pass": "transport:read",
    "/transport/fees": "transport:read",
    "/transport/bus-attendance": "transport:read",
    "/transport/route-change-approval": "transport:read",
    "/transport/gps-tracking": "transport:read",
    "/placement/company-database": "placement:read",
    "/placement/campus-drives": "placement:read",
    "/placement/student-eligibility-filter": "placement:read",
    "/placement/selected-student-tracking": "placement:read",
    "/placement/cv-upload": "placement:read",
    "/placement/student-registration": "placement:read",
    "/placement/interview-tracking": "placement:read",
    "/placement/offer-letters": "placement:read",
    "/placement/analytics": "placement:read",
    "/placement/alumni-interaction": "placement:read",
    "/events/workshops": "events:read",
    "/events/seminar-registration": "events:read",
    "/events/certificates": "events:read",
    "/accreditation/faculty-qualification": "accreditation:read",
    "/accreditation/student-strength": "accreditation:read",
    "/accreditation/infrastructure": "accreditation:read",
    "/accreditation/research-publication": "accreditation:read",
    "/reports/builder": "reports:read",
    "/reports/export-excel": "reports:read",
    "/reports/export-pdf": "reports:read",
    "/analytics": "analytics:read",
    "/analytics/department-performance": "analytics:read",
    "/audit/activity": "audit:read",
    "/audit/login-logs": "audit:read",
    "/audit/data-modification": "audit:read",
    "/audit/security": "audit:read",
    "/approvals": "approvals:read",
    "/sessions": "sessions:read",
    "/audit": "audit:read",
    "/permissions": "role_management:read",
    "/users": "users:read",
    "/settings/backup": "role_management:write",
    "/settings/payment-gateway": "role_management:write",
    "/settings/email": "role_management:write",
    "/settings/multi-campus": "role_management:write",
    "/profile": "dashboard:read",
    "/parent": "parent_portal:read",
    "/parent-inbox": "attendance:write",
    "/student/marks": "student_portal:read",
    "/student/fees": "student_portal:read",
    "/student/payments": "student_portal:read",
    "/student/notices": "student_portal:read",
    "/student/messaging": "student_portal:read",
    "/student/certificates": "student_portal:read|certificates:read",
}
